services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress-app
    ports:
      - "8000:80" # WordPress accessible on port 8000
      - "4430:443" # SSL port for testing, optional
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content # Mounts the host's wp-content directory into the container
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wordpress-db
    ports:
      - "3307:3306" # MySQL port mapped to avoid conflicts
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/tmp/db # Mounts the host's db directory into the container at /tmp/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80" # phpMyAdmin accessible on port 8080
    depends_on:
      - db

volumes:
  db_data: